version: '3.8'

services:
  app:
    build: .
    container_name: shopper_backend_test
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.13-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: